server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gizmo_deck
    username: root
    password: arman5911

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: armaanali.dev@gmail.com
    password: grua slqy snnl cjvl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true